[features]
seeds = false
skip-lint = false

[programs.localnet]
constants = "ATqP7TbxPzSYd2nTbXo1usji5Ftq4QRae93SvDzD89yy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/theoroque/.config/solana/cli/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
